gems:
  - jekyll-feed

url: http://tbates.github.io
# Note - if you enable this, use jekyll --baseurl '/' to view locally
# baseurl: /

# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: "umx!"
# Short description (goes below the title; it will also be used in the RSS feed)
description: "Tutorial help doing Structural Equation Modeling in R using the umx and OpenMx packages."

# url for [snaptortoise](https://github.com/snaptortoise/jekyll-rss-feeds)
